# Generated by Django 4.0.7 on 2022-10-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_croppedimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimg',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='croppedimg',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
