# Docker compose file for PRODUCTION deployment
---
version: '3.7'

services:
  elasticsearch:
    container_name: es_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false # security is disabled on development
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
    extra_hosts:
      - "host.docker.internal:host-gateway"
  kibana:
    container_name: kb_container
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es_container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn ACMAS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_files:/home/app/web/staticfiles
      - media_files:/home/app/web/mediafiles
    expose:
      - 8000  # Port 8000 is only exposed internally
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/web/staticfiles
      - media_files:/home/app/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web
      - db
networks:
  es-net:
    driver: bridge
volumes:
  postgres_data:
  static_files:
  media_files:
