version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # To persist the data beyond the life of the container
    environment:  # Defines name for default db, User/PW
      - POSTGRES_USER=hello_acmas
      - POSTGRES_PASSWORD=hello_acmas
      - POSTGRES_DB=hello_acmas_dev

volumes:
  postgres_data: