# Docker compose file for Django CI/CD GitHub Action

version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn ACMAS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000  # Port 8000 is only exposed internally
    environment:
      DATABASE: postgres
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      SQL_DATABASE: acmas_db
      SQL_ENGINE: django.db.backends.postgresql
      SQL_HOST: db
      SQL_PASSWORD: acmas_dev
      SQL_PORT: 5432
      SQL_USER: acmas_dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: acmas_db
      POSTGRES_PASSWORD: acmas_dev
      POSTGRES_USER: acmas_dev
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: