---
version: '3.8'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false # security is disabled on development
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      # To persist the data beyond the life of the container
      - postgres_data:/var/lib/postgresql/data/
    environment:  # Defines name for default db, User/PW
      - POSTGRES_USER=hello_acmas
      - POSTGRES_PASSWORD=hello_acmas
      - POSTGRES_DB=hello_acmas_dev
networks:
  es-net:
    driver: bridge
volumes:
  postgres_data: